name: Bug Report or Feature Request
description: File a bug report or request a new feature... llm template so sorry if it breaks
title: "[BUG/FEATURE]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Bug
        - Feature Request
        - Documentation Issue
        - Question
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue.
      placeholder: Tell us what you see or want to see!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: What actually happened?
      placeholder: Describe what actually happened.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 14.17.0
          - **npm**: 6.14.13
      value: |
        - OS:
        - Node:
        - npm:
      render: markdown
    validations:
      required: false
