name = "kalsima-backend"
main = ".output/server/index.mjs"

[build]
command = "npm run build"

[site]
bucket = ".output/public"

[vars]
NODE_VERSION = "20.5.0"

[env.production]
node_compat = true

[triggers]
crons = []

[[kv_namespaces]]
id = "e3d98bd235f38411b4cfefb2567578cf"
preview_id = "e3d98bd235f38411b4cfefb2567578cf"
binding = "KALSIMA_KV"
